accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("register/", views.register, name='register'),
    path("login/", views.login, name='login'),
    path("logout/", views.logout, name='logout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path("uavs/", include('ihas.urls')),
    path("accounts/", include('accounts.urls')),
    path('api/', include('rest.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
<!-- FOOTER -->
<footer class="bg-white text-dark">
    <div class="text-center">
        <p class="fs-5 py-3 mb-0">Tüm hakları saklıdır | <a href="#" class="text-dark fst-italic">Ataberk Özyılmaz</a></p>
    </div>
</footer>
<!-- FOOTER END -->

templates/includes/navbar.html
<header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-md-4 pt-1">
            <a class="blog-header-logo text-dark text-decoration-none" href="{% url 'home' %}">IHA KİRALAMA</a>
        </div>
        <div class="col-md-4">
            <form action="{% url 'search' %}" method="GET">
                <div class="input-group">
                    <input class="form-control" type="text" name="keyword" value="{{ keyword }}" placeholder="IHA ARA.."
                           aria-label="Enter search term..." aria-describedby="button-search"/>
                    <button class="btn btn-warning" id="button-search" type="submit">ARA!</button>
                </div>
            </form>
        </div>
        <div class="col-md-4 d-flex justify-content-end align-items-center">
            {% if not user.is_authenticated %}
            <a class="btn btn-sm btn-warning" href="{% url 'accounts:login' %}">Giriş</a> &nbsp;
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'accounts:register' %}">Kayıt Ol</a>
            {% else %}
                <span><a href="{% url 'all-uavs' %}" class="btn btn-sm btn-outline-secondary">IHALAR</a></span>
                &emsp;
                <span><a class="btn btn-sm btn-outline-danger" href="{% url 'accounts:logout' %}">Çıkış</a></span>
            {% endif %}
        </div>
    </div>
</header>

<div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
        {% for category in categories %}
            <a class="text-decoration-none p-2 text-muted"
               href="{% url 'uavs_by_category' category.category_slug %}">{{ category.category_name }}</a>
        {% endfor %}
    </nav>
</div>